name: First Action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8.18, 3.9.17, 3.10.12, 3.11.4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          
      - name: Run Tests
        run: |
          echo "Running tests..."
          cd src
          python -m pytest add.py
          echo "Tests completed."

